### ISSUE TITLE
ESM support

### ISSUE THREAD

**Issue by Tatamethues** [konvajs/react-konva#504]
I'm using this package with snowpack. I tried both konva.js and react konva. Konva.js works good, but react-konva caused error `import not found: Layer`

**Comment by lavrton** [comment]
Hmm. Snowpack doesn't work with common js modules? Can you make a very small repo to reproduce?

**Comment by dazzito** [comment]
Getting the same issue with snowpack when trying to import shapes. Adding `"install": ["react-konva/lib/ReactKonvaCore"]` to snowpack.config works.

**Comment by alobe** [comment]
> Hmm. Snowpack doesn't work with common js modules? Can you make a very small repo to reproduce?

it seems also have same issue on using it with [https://github.com/vitejs/vite/issues/162#issuecomment-629727688](vite), here is [https://github.com/alobe/vite-konva](the small repo) you could check it out 😋

**Comment by lavrton** [comment]
I just published `react-konva@17.0.1-0`. Probably it will fix the issue with snowpack. Please try it.

**Comment by lavrton** [comment]
@alobe I tried your repo. It worked ok for me.

Can someone create a very small demo with snowpack?
@ludwignagelhus probably you can help too.

**Comment by ludwignagelhus** [comment]
https://github.com/ludwignagelhus/snowpack_react_konva_demo

**Comment by lavrton** [comment]
Fixed with `react-konva@17.0.1-1`.

**Comment by ludwignagelhus** [comment]
Did it work for you @lavrton ?

**Comment by lavrton** [comment]
Yes. I was using your testing repo. Thanks for it.

**Comment by ludwignagelhus** [comment]
Okay. I am still getting the error. Perhaps I need to update Node or something.

**Comment by lavrton** [comment]
Did you install `17.0.1-1`?

If it doesn't work for you, please update the repo with your last install.

**Comment by ludwignagelhus** [comment]
I got it working. I deleted my `node_modules` and `package-lock.json` and ran `npm install`. That got stuff working!

For anybody who haven't tried Snowpack: being able to refrash your code and also keep the Apps react state is golden - highly reccomend giving it a go!
